apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: devops-route
spec:
  to:
    kind: Service
    name: devops-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
