name: Build and Deploy to OpenShift

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: andreaepis78/myapp

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Login to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin <<< "${{ secrets.DOCKER_PASS }}"

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Login to OpenShift
        run: |
          oc login "${{ secrets.OCP_SERVER }}" --token="${{ secrets.OCP_TOKEN }}"

      - name: Deploy with Helm
        run: |
          helm template devops-app ./helm/devops-app \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }} \
          | oc apply -n andreasandro-dev -f -
