name: Build and Deploy to OpenShift

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Login Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      
      - name: Push image
        run: |
          docker tag myapp:latest andreaepis78/myapp:latest
          docker push andreaepis78/myapp:latest

      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OCP_SERVER }} --token=${{ secrets.OCP_TOKEN }}

      - name: Deploy with Helm to OpenShift
        if: github.event_name == 'workflow_dispatch'
        run: |
          helm template devops-app ./helm/devops-app \
            --set image.repository=andreaepis78/myapp \
            --set image.tag=latest \
          | oc apply -n andreasandro-dev -f -
